name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-13
    
    timeout-minutes: 10
    
    steps:
    - uses: actions/checkout@v3

    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

    - name: Build and test iOS
      run: xcodebuild clean build test -workspace Essential.xcworkspace -scheme "CI_iOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 14,OS=16.4" ONLY_ACTIVE_ARCH=YES

    - name: Build and test macOS
      run: xcodebuild clean build test -workspace Essential.xcworkspace -scheme "CI_macOS" -destination "platform=macOS" -sdk macosx CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
